//go:build integration

package runtime_test

// TestE2E_StreamStreamJoin is the P4b-F2-C6 exit criterion test.
//
// Proves the full DSL→adapter→broker round-trip for the stream-stream windowed join:
//
//  1. LEFT_THEN_RIGHT: left arrives before right; both within window → emit "L+R".
//  2. RIGHT_THEN_LEFT: right arrives before left; both within window → emit "L+R".
//     (Proves symmetry: both left and right processors + merge node fire.)
//  3. OUT_OF_WINDOW: right record whose timestamp is far outside any left window
//     produces NO emit for that key. A control key proves the pipeline is live.
//  4. RESTORE: produce a left record, wait until it is durable in the left store's
//     changelog, cancel client1 (delete partition dir), restart as client2, wait for
//     OnAssigned (restore), then produce a matching right record and assert the join
//     fires — proving the buffered-left-record was restored from changelog.
//
// Topology (1 partition each — co-partitioned trivially):
//
//	leftTopic  → Stream[string,string]("lsrc") ─┐
//	                                             ├─ Join (ssjoin) ─ ssjoin-merge-5 → outTopic
//	rightTopic → Stream[string,string]("rsrc") ─┘
//
// JoinWindows{Before: 5s, After: 5s, Grace: 1s} — symmetric window, much larger
// than all timestamp deltas in the test.
//
// Store names (counter starts at 0 when builder is fresh for each topology call):
//
//	leftStoreName  = "ssjoin-left-store-0"
//	rightStoreName = "ssjoin-right-store-1"
//
// Changelog topic name derivation (allChangelogTopics: appID + "-" + storeName + "-changelog"):
//
//	leftChangelog  = appID + "-ssjoin-left-store-0-changelog"
//	rightChangelog = appID + "-ssjoin-right-store-1-changelog"
//
// Event-time mechanism: kgo.Record.Timestamp is set explicitly for each produced
// record. The Adapter reads in.Timestamp.UnixMilli() → topology.Record.Timestamp,
// which the join processors use as ts (no custom extractorFn).
//
// Deterministic sync: all waits are changelog-poll or output-poll loops with
// bounded timeouts and t.Fatalf on expiry. No bare time.Sleep.
//
// CRITICAL (anti-missing-subscription check): kafka.New receives
// adapter.SourceTopics() — both leftTopic and rightTopic — so the consumer
// subscribes to BOTH. Passing only one topic starves the other source; joins miss.

import (
	"bytes"
	"context"
	"encoding/binary"
	"encoding/json/v2"
	"log/slog"
	"os"
	"path/filepath"
	"testing"
	"time"

	gstream "mortz.dev/go/gstream"
	"mortz.dev/go/gstream/internal/kafka"
	"github.com/testcontainers/testcontainers-go"
	kafkamodule "github.com/testcontainers/testcontainers-go/modules/kafka"
	kgo "github.com/twmb/franz-go/pkg/kgo"
)

func TestE2E_StreamStreamJoin(t *testing.T) {
	if !dockerAvailable() {
		t.Skip("Docker not available; skipping stream-stream join E2E integration test")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 300*time.Second)
	defer cancel()

	// --- 1. Start Kafka broker ---
	kc, err := kafkamodule.Run(ctx, "confluentinc/cp-kafka:7.4.0",
		kafkamodule.WithClusterID("test-cluster-ssjoin"),
		testcontainers.WithEnv(map[string]string{
			"KAFKA_AUTO_CREATE_TOPICS_ENABLE": "false",
		}),
	)
	if err != nil {
		t.Skipf("failed to start Kafka container: %v", err)
	}
	t.Cleanup(func() { _ = kc.Terminate(context.Background()) })

	brokers, err := kc.Brokers(ctx)
	if err != nil {
		t.Fatalf("get brokers: %v", err)
	}
	t.Logf("brokers: %v", brokers)

	const (
		appID      = "ssjoin-e2e"
		leftTopic  = "ssj-left"
		rightTopic = "ssj-right"
		outTopic   = "ssj-out"

		// Store names are generated by builder.nextName (counter starts at 0 per
		// fresh StreamBuilder):
		//   Stream("lsrc")  → counter unchanged (source nodes don't call nextName)
		//   Stream("rsrc")  → counter unchanged
		//   Join  → calls nextName("ssjoin-left-store")  → "ssjoin-left-store-0",  counter=1
		//         → calls nextName("ssjoin-right-store") → "ssjoin-right-store-1", counter=2
		//         → calls nextName("ssjoin-left")        → "ssjoin-left-2",        counter=3
		//         → calls nextName("ssjoin-right")       → "ssjoin-right-3",       counter=4
		//         → calls nextName("ssjoin-merge")       → "ssjoin-merge-4",       counter=5
		//
		// Changelog topics: allChangelogTopics() = appID + "-" + storeName + "-changelog"
		leftStoreName  = "ssjoin-left-store-0"
		rightStoreName = "ssjoin-right-store-1"
		leftChangelog  = appID + "-" + leftStoreName + "-changelog"
		rightChangelog = appID + "-" + rightStoreName + "-changelog"
	)

	// --- 2. Temp state dir ---
	stateDir, err := os.MkdirTemp("", "gstream-ssjoin-e2e-*")
	if err != nil {
		t.Fatalf("mktemp: %v", err)
	}
	defer os.RemoveAll(stateDir)
	t.Logf("stateDir: %s", stateDir)

	// --- 3. Create topics (1 partition each — co-partitioning trivially holds) ---
	if err := kafka.EnsureTopics(ctx, brokers, []kafka.TopicSpec{
		{Name: leftTopic, Partitions: 1, ReplicationFactor: 1},
		{Name: rightTopic, Partitions: 1, ReplicationFactor: 1},
		{Name: outTopic, Partitions: 1, ReplicationFactor: 1},
		{Name: leftChangelog, Partitions: 1, ReplicationFactor: 1,
			Configs: map[string]string{"cleanup.policy": "compact"}},
		{Name: rightChangelog, Partitions: 1, ReplicationFactor: 1,
			Configs: map[string]string{"cleanup.policy": "compact"}},
	}); err != nil {
		t.Fatalf("EnsureTopics: %v", err)
	}
	t.Logf("topics created: %s, %s, %s, %s, %s",
		leftTopic, rightTopic, outTopic, leftChangelog, rightChangelog)

	// --- 4. Validate co-partitioning ---
	if err := kafka.ValidateCoPartitioned(ctx, brokers, []string{leftTopic, rightTopic}); err != nil {
		t.Fatalf("ValidateCoPartitioned: %v", err)
	}

	cfg, err := gstream.Configure(
		gstream.WithName(appID),
		gstream.WithBrokers(brokers...),
		gstream.WithStateDir(stateDir),
	)
	if err != nil {
		t.Fatalf("Configure: %v", err)
	}

	// ==========================================================================
	// PHASE 1: LEFT_THEN_RIGHT, RIGHT_THEN_LEFT, OUT_OF_WINDOW
	// ==========================================================================

	bt1 := buildSSJoinTopology(leftTopic, rightTopic, outTopic)

	adapter1, err := newTestAdapter(bt1, cfg, slog.Default())
	if err != nil {
		t.Fatalf("NewAdapter p1: %v", err)
	}

	// CRITICAL anti-subscription check: assert adapter1.SourceTopics() contains BOTH.
	srcTopics1 := adapter1.SourceTopics()
	t.Logf("source topics: %v", srcTopics1)
	{
		hasLeft, hasRight := false, false
		for _, tp := range srcTopics1 {
			if tp == leftTopic {
				hasLeft = true
			}
			if tp == rightTopic {
				hasRight = true
			}
		}
		if !hasLeft || !hasRight {
			t.Fatalf("SourceTopics missing: hasLeft=%v hasRight=%v; got %v", hasLeft, hasRight, srcTopics1)
		}
		t.Logf("SourceTopics confirmed: %q and %q both subscribed", leftTopic, rightTopic)
	}

	client1, err := kafka.New(cfg, srcTopics1, slog.Default(),
		kafka.WithLifecycle(adapter1.LifecycleCallbacks()),
		kafka.WithPostBatch(adapter1.PostBatchHook()),
		kafka.WithHealthGate(adapter1.HealthGateHook()),
	)
	if err != nil {
		t.Fatalf("kafka.New p1: %v", err)
	}

	// Set up output consumer at start so no records are missed.
	outConsumer, err := kgo.NewClient(
		kgo.SeedBrokers(brokers...),
		kgo.ConsumePartitions(map[string]map[int32]kgo.Offset{
			outTopic: {0: kgo.NewOffset().AtStart()},
		}),
	)
	if err != nil {
		t.Fatalf("outConsumer: %v", err)
	}
	defer outConsumer.Close()

	run1Ctx, run1Cancel := context.WithCancel(ctx)
	done1 := make(chan error, 1)
	go func() { done1 <- client1.Run(run1Ctx, adapter1.ProcessFunc()) }()

	ks := JSONSerde[string]{}

	// --- Case 1: LEFT_THEN_RIGHT ---
	// left(k1, "L1", ts=10000) then right(k1, "R1", ts=10001).
	// delta=1ms < After=5000ms → within window.
	// Expect out: k1 → "L1+R1".
	produceSSJoinRecord(t, ctx, brokers, leftTopic, "k1", "L1", 10_000, ks)
	produceSSJoinRecord(t, ctx, brokers, rightTopic, "k1", "R1", 10_001, ks)
	t.Log("case-1 LEFT_THEN_RIGHT: produced left(k1,L1,ts=10000) right(k1,R1,ts=10001)")

	ltrRecs := ssJoinWaitOutput(t, ctx, outConsumer, 1, 30*time.Second)
	var ltrHit *ssJoinOutputRecord
	for i := range ltrRecs {
		if ltrRecs[i].key == "k1" && ltrRecs[i].value == "L1+R1" {
			ltrHit = &ltrRecs[i]
			break
		}
	}
	if ltrHit == nil {
		t.Errorf("LEFT_THEN_RIGHT: expected output key=k1 value=L1+R1, got %v", ltrRecs)
	} else {
		t.Logf("LEFT_THEN_RIGHT PASSED: %v", *ltrHit)
	}

	// --- Case 2: RIGHT_THEN_LEFT ---
	// right(k2, "R2", ts=20000) then left(k2, "L2", ts=20002).
	// delta=2ms < Before=5000ms → within window.
	// Expect out: k2 → "L2+R2".
	produceSSJoinRecord(t, ctx, brokers, rightTopic, "k2", "R2", 20_000, ks)
	produceSSJoinRecord(t, ctx, brokers, leftTopic, "k2", "L2", 20_002, ks)
	t.Log("case-2 RIGHT_THEN_LEFT: produced right(k2,R2,ts=20000) left(k2,L2,ts=20002)")

	rtlRecs := ssJoinWaitOutput(t, ctx, outConsumer, 1, 30*time.Second)
	var rtlHit *ssJoinOutputRecord
	for i := range rtlRecs {
		if rtlRecs[i].key == "k2" && rtlRecs[i].value == "L2+R2" {
			rtlHit = &rtlRecs[i]
			break
		}
	}
	if rtlHit == nil {
		t.Errorf("RIGHT_THEN_LEFT: expected output key=k2 value=L2+R2, got %v", rtlRecs)
	} else {
		t.Logf("RIGHT_THEN_LEFT PASSED: %v", *rtlHit)
	}

	// --- Case 3: OUT_OF_WINDOW ---
	// left(k3@50000) + right(k3@62000): gap=12000ms > After=5000ms → no join.
	//   right@62000 scans left for [62000-6000=56000, 62000+5000=67000]; left@50000 < 56000 → miss.
	//   left@50000 scans right for [50000-6000=44000, 50000+5000=55000]; right hasn't arrived yet → miss.
	// Stream time after right@62000: streamTime=62000. lateBoundary=62000-10000-1000=51000.
	// ctrl pair at ts=62001/62002 > 51001/51002 → NOT late-dropped.
	// ctrl-right@62002 scans left for [62002-6000=56002, 62002+5000=67002]; ctrl-left@62001 ✓ → emit.
	produceSSJoinRecord(t, ctx, brokers, leftTopic, "k3", "L3", 50_000, ks)
	produceSSJoinRecord(t, ctx, brokers, rightTopic, "k3", "R3-oop", 62_000, ks)
	// Control pair: timestamps just above the out-of-window records → not late-dropped.
	produceSSJoinRecord(t, ctx, brokers, leftTopic, "kctrl", "Lctrl", 62_001, ks)
	produceSSJoinRecord(t, ctx, brokers, rightTopic, "kctrl", "Rctrl", 62_002, ks)
	t.Log("case-3 OUT_OF_WINDOW: produced k3 out-of-window pair (ts=50000/62000) and ctrl pair (ts=62001/62002)")

	// Collect output until ctrl arrives; k3 must not appear.
	ctrlFound := false
	for !ctrlFound {
		batch := ssJoinWaitOutput(t, ctx, outConsumer, 1, 30*time.Second)
		if len(batch) == 0 {
			t.Fatal("OUT_OF_WINDOW: timed out waiting for ctrl output")
		}
		for _, r := range batch {
			if r.key == "kctrl" && r.value == "Lctrl+Rctrl" {
				ctrlFound = true
				t.Logf("OUT_OF_WINDOW: ctrl output arrived %v", r)
			}
			if r.key == "k3" {
				t.Errorf("OUT_OF_WINDOW violation: k3 appeared in output with value=%q (no left for k3 existed)", r.value)
			}
		}
	}
	t.Log("OUT_OF_WINDOW PASSED: k3 absent, ctrl confirmed")

	// --- Phase 1 shutdown ---
	run1Cancel()
	select {
	case err := <-done1:
		if err != nil {
			t.Errorf("client1.Run returned error: %v", err)
		}
	case <-time.After(15 * time.Second):
		t.Fatal("client1.Run did not stop within 15s")
	}
	client1.Close()
	t.Log("phase-1: shutdown complete")

	// ==========================================================================
	// PHASE 2: RESTORE (the make-or-break path)
	//
	// Strategy:
	//   a. Use a FRESH topology instance (new counter → same store names as phase-1).
	//   b. Produce left(krestore, "Lrestore", ts=40000).
	//   c. Wait until "Lrestore" is durable in the LEFT store changelog.
	//   d. Cancel client1b, delete partition dir (force restore from changelog).
	//   e. Start client2, wrap OnAssigned → restoreDone channel.
	//   f. Wait for restoreDone (RestoreFromChangelog replayed left store).
	//   g. Produce right(krestore, "Rrestore", ts=40001) — within window.
	//   h. Assert out: krestore → "Lrestore+Rrestore".
	//      Proves: buffered-left was restored from changelog; join fired post-restart.
	// ==========================================================================

	bt1b := buildSSJoinTopology(leftTopic, rightTopic, outTopic)
	adapter1b, err := newTestAdapter(bt1b, cfg, slog.Default())
	if err != nil {
		t.Fatalf("NewAdapter p1b: %v", err)
	}

	srcTopics1b := adapter1b.SourceTopics()
	client1b, err := kafka.New(cfg, srcTopics1b, slog.Default(),
		kafka.WithLifecycle(adapter1b.LifecycleCallbacks()),
		kafka.WithPostBatch(adapter1b.PostBatchHook()),
		kafka.WithHealthGate(adapter1b.HealthGateHook()),
	)
	if err != nil {
		t.Fatalf("kafka.New p1b: %v", err)
	}

	run1bCtx, run1bCancel := context.WithCancel(ctx)
	done1b := make(chan error, 1)
	go func() { done1b <- client1b.Run(run1bCtx, adapter1b.ProcessFunc()) }()

	// Produce left(krestore, "Lrestore", ts=70000).
	// Phase-1 reached stream_time=62002 (ctrl-right@62002). That value is persisted
	// to Pebble at closeTask, so client1b inherits it from the EXISTING partition dir
	// (RemoveAll has not run yet). For left@70000 not to be late-dropped by client1b:
	//   lateBoundary = 62002 - 10000 - 1000 = 51002; 70000 > 51002 ✓.
	// After RemoveAll + restart, client2 opens a FRESH Pebble dir; ReadStreamTime
	// returns (0, false, nil) → stream_time resets to 0. The right record at ts=70001
	// is never late-dropped (lateBoundary = 70001-10000-1000 = 59001; 70001 > 59001 ✓),
	// and ts=70001 would also survive the inherited-62002 boundary (70001 > 51002 ✓),
	// so the RESTORE case is robust under both stream-time-0 and stream-time-inherited.
	produceSSJoinRecord(t, ctx, brokers, leftTopic, "krestore", "Lrestore", 70_000, ks)
	t.Log("restore-phase: produced left(krestore,Lrestore,ts=70000)")

	// Deterministic wait: poll leftChangelog until "Lrestore" entry is durable.
	// The left processor calls WindowPut(kBytes, ts=70000, v1Bytes) → changelog key
	// encodes as: leftStoreName + 0x00 + WindowCompositeKey(kBytes, 70000).
	pollSSJoinChangelog(t, ctx, brokers, leftChangelog, leftStoreName, ks, "krestore", 70_000)
	t.Log("restore-phase: left changelog confirmed krestore@70000 durable")

	// Shutdown client1b BEFORE deleting partition dir.
	run1bCancel()
	select {
	case err := <-done1b:
		if err != nil {
			t.Logf("client1b.Run returned (expected on cancel): %v", err)
		}
	case <-time.After(15 * time.Second):
		t.Fatal("client1b did not stop within 15s")
	}
	client1b.Close()

	// Delete local Pebble partition dir to force changelog restore on restart.
	partitionDir := filepath.Join(stateDir, appID, "partition-0")
	if err := os.RemoveAll(partitionDir); err != nil {
		t.Fatalf("RemoveAll partition dir: %v", err)
	}
	t.Logf("restore-phase: deleted partition dir %s", partitionDir)

	// Build client2 — same appID+stateDir → same store names → same changelog topics.
	bt2 := buildSSJoinTopology(leftTopic, rightTopic, outTopic)
	adapter2, err := newTestAdapter(bt2, cfg, slog.Default())
	if err != nil {
		t.Fatalf("NewAdapter p2: %v", err)
	}

	// Wrap OnAssigned to detect when RestoreFromChangelog completes.
	restoreDone := make(chan struct{}, 1)
	onAssigned2, onRevoked2 := adapter2.LifecycleCallbacks()
	wrappedAssigned := func(ctx context.Context, assigned map[string][]int32) error {
		err := onAssigned2(ctx, assigned)
		if err == nil {
			select {
			case restoreDone <- struct{}{}:
			default:
			}
		}
		return err
	}

	srcTopics2 := adapter2.SourceTopics()
	client2, err := kafka.New(cfg, srcTopics2, slog.Default(),
		kafka.WithLifecycle(wrappedAssigned, onRevoked2),
		kafka.WithPostBatch(adapter2.PostBatchHook()),
		kafka.WithHealthGate(adapter2.HealthGateHook()),
	)
	if err != nil {
		t.Fatalf("kafka.New p2: %v", err)
	}

	run2Ctx, run2Cancel := context.WithCancel(ctx)
	defer run2Cancel()
	done2 := make(chan error, 1)
	go func() { done2 <- client2.Run(run2Ctx, adapter2.ProcessFunc()) }()

	// Wait for OnAssigned (RestoreFromChangelog complete).
	select {
	case <-restoreDone:
		t.Log("restore-phase: OnAssigned fired; RestoreFromChangelog complete")
	case <-time.After(30 * time.Second):
		t.Fatal("restore-phase: timed out waiting for OnAssigned/restore")
	}

	// Produce right(krestore, "Rrestore", ts=70001) — within window of left@70000.
	// After restore, left store has krestore@70000="Lrestore". Right processor scans
	// left store for ts in [70001-5000-1000=64001, 70001+5000=75001] → finds @70000.
	// joiner("Lrestore","Rrestore") = "Lrestore+Rrestore".
	produceSSJoinRecord(t, ctx, brokers, rightTopic, "krestore", "Rrestore", 70_001, ks)
	t.Log("restore-phase: produced right(krestore,Rrestore,ts=70001) post-restart")

	// Poll output; outConsumer started at offset 0 so may still deliver earlier records.
	// Scan until we find key=krestore value=Lrestore+Rrestore.
	const restoreWant = "Lrestore+Rrestore"
	var restoreHit *ssJoinOutputRecord
	for restoreHit == nil {
		batch := ssJoinWaitOutput(t, ctx, outConsumer, 1, 30*time.Second)
		if len(batch) == 0 {
			break
		}
		for i := range batch {
			if batch[i].key == "krestore" && batch[i].value == restoreWant {
				restoreHit = &batch[i]
				break
			}
		}
	}
	if restoreHit == nil {
		t.Errorf("RESTORE: did not receive key=krestore value=%q — left record was NOT restored from changelog (or join did not fire)", restoreWant)
	} else {
		t.Logf("RESTORE PASSED: %v — post-restart right record joined pre-restart restored left record", *restoreHit)
	}

	run2Cancel()
	select {
	case err := <-done2:
		if err != nil {
			t.Errorf("client2.Run returned error: %v", err)
		}
	case <-time.After(15 * time.Second):
		t.Fatal("client2.Run did not stop within 15s")
	}
	client2.Close()
}

// ─── topology ────────────────────────────────────────────────────────────────

// buildSSJoinTopology constructs:
//
//	Stream[string,string](leftTopic, "lsrc") ─┐
//	                                           ├─ Join(joiner, JoinWindows{5s,5s,1s}) ─ To(outTopic, "out")
//	Stream[string,string](rightTopic, "rsrc") ─┘
//
// joiner: func(l,r string) string { return l+"+"+r }
// JoinWindows{Before:5s, After:5s, Grace:1s}: symmetric, much larger than test deltas.
func buildSSJoinTopology(leftTopic, rightTopic, outTopic string) *gstream.BuiltTopology {
	b := gstream.NewStreamBuilder()
	ks := JSONSerde[string]{}
	vs := JSONSerde[string]{}
	outSerde := JSONSerde[string]{}

	left := gstream.Stream[string, string](b, leftTopic, "lsrc", ks, vs)
	right := gstream.Stream[string, string](b, rightTopic, "rsrc", ks, vs)

	joined := left.Join[string, string](
		right,
		func(l, r string) string { return l + "+" + r },
		gstream.JoinWindows{
			Before: 5 * time.Second,
			After:  5 * time.Second,
			Grace:  1 * time.Second,
		},
		ks, vs, vs, outSerde,
	)
	joined.To(outTopic, "out", ks, outSerde)

	return b.Build()
}

// ─── helpers ─────────────────────────────────────────────────────────────────

// ssJoinOutputRecord is a decoded record from the output topic.
type ssJoinOutputRecord struct {
	key   string
	value string
}

func (r ssJoinOutputRecord) String() string {
	return "{key=" + r.key + " value=" + r.value + "}"
}

// produceSSJoinRecord produces a single record with an explicit event-time timestamp.
// kgo.Record.Timestamp drives the join window via Adapter → topology.Record.Timestamp.
func produceSSJoinRecord(
	t *testing.T,
	ctx context.Context,
	brokers []string,
	topic, key, value string,
	tsMs int64,
	serde JSONSerde[string],
) {
	t.Helper()
	kb, _ := serde.Serialize(key)
	vb, _ := serde.Serialize(value)
	producer, err := kgo.NewClient(kgo.SeedBrokers(brokers...))
	if err != nil {
		t.Fatalf("produceSSJoinRecord: new client: %v", err)
	}
	defer producer.Close()
	rec := &kgo.Record{
		Topic:     topic,
		Key:       kb,
		Value:     vb,
		Timestamp: time.UnixMilli(tsMs), // explicit event-time for deterministic window math
	}
	res := producer.ProduceSync(ctx, rec)
	if res.FirstErr() != nil {
		t.Fatalf("produceSSJoinRecord: topic=%s key=%q ts=%d: %v", topic, key, tsMs, res.FirstErr())
	}
}

// pollSSJoinChangelog polls the specified changelog topic until a WindowPut entry
// for (key, windowStart) appears. Calls t.Fatalf on 30s timeout.
//
// Changelog key format (matches WindowPut's Mutation.Key via KeyValueStore):
//
//	storeName + 0x00 + WindowCompositeKey(kBytes, windowStart)
//	= storeName + 0x00 + uint32(len(kBytes)) big-endian + kBytes + int64(windowStart) big-endian
//
// The value is the raw serialized value bytes (JSONSerde[string] encoded string).
func pollSSJoinChangelog(
	t *testing.T,
	ctx context.Context,
	brokers []string,
	topic, storeName string,
	serde JSONSerde[string],
	wantKey string,
	wantWindowStart int64,
) {
	t.Helper()

	readyCtx, cancel := context.WithTimeout(ctx, 30*time.Second)
	defer cancel()

	consumer, err := kgo.NewClient(
		kgo.SeedBrokers(brokers...),
		kgo.ConsumePartitions(map[string]map[int32]kgo.Offset{
			topic: {0: kgo.NewOffset().AtStart()},
		}),
	)
	if err != nil {
		t.Fatalf("pollSSJoinChangelog: create consumer: %v", err)
	}
	defer consumer.Close()

	prefix := append([]byte(storeName), 0x00)
	kBytes, _ := serde.Serialize(wantKey)
	targetComposite := ssJoinWindowCompositeKeyLocal(kBytes, wantWindowStart)
	targetFull := make([]byte, len(prefix)+len(targetComposite))
	copy(targetFull, prefix)
	copy(targetFull[len(prefix):], targetComposite)

	found := false
	for !found {
		fetches := consumer.PollFetches(readyCtx)
		if fetches.IsClientClosed() {
			break
		}
		if err := readyCtx.Err(); err != nil {
			t.Fatalf("pollSSJoinChangelog: timed out waiting for key=%q windowStart=%d in %s",
				wantKey, wantWindowStart, topic)
		}
		fetches.EachRecord(func(r *kgo.Record) {
			if bytes.Equal(r.Key, targetFull) && len(r.Value) > 0 {
				found = true
			}
		})
	}
}

// ssJoinWindowCompositeKeyLocal mirrors state.WindowCompositeKey (no import cycle).
// Format: uint32(len(kBytes)) big-endian | kBytes | int64(windowStart) big-endian.
func ssJoinWindowCompositeKeyLocal(kBytes []byte, windowStart int64) []byte {
	out := make([]byte, 4+len(kBytes)+8)
	binary.BigEndian.PutUint32(out[0:4], uint32(len(kBytes)))
	copy(out[4:], kBytes)
	binary.BigEndian.PutUint64(out[4+len(kBytes):], uint64(windowStart))
	return out
}

// ssJoinWaitOutput polls outConsumer until n records arrive or timeout elapses.
// Returns whatever records arrived within the timeout.
func ssJoinWaitOutput(
	t *testing.T,
	ctx context.Context,
	consumer *kgo.Client,
	n int,
	timeout time.Duration,
) []ssJoinOutputRecord {
	t.Helper()
	serde := JSONSerde[string]{}
	readyCtx, cancel := context.WithTimeout(ctx, timeout)
	defer cancel()

	var out []ssJoinOutputRecord
	for len(out) < n {
		fetches := consumer.PollFetches(readyCtx)
		if fetches.IsClientClosed() {
			break
		}
		if err := readyCtx.Err(); err != nil {
			break
		}
		fetches.EachRecord(func(r *kgo.Record) {
			key, err := serde.Deserialize(r.Key)
			if err != nil {
				t.Logf("ssJoinWaitOutput: skip (key decode): %v", err)
				return
			}
			value, err := serde.Deserialize(r.Value)
			if err != nil {
				t.Logf("ssJoinWaitOutput: skip (val decode): %v", err)
				return
			}
			out = append(out, ssJoinOutputRecord{key: key, value: value})
			t.Logf("ssJoinWaitOutput: received key=%s value=%s", key, value)
		})
	}
	return out
}

// ssJoinDecodeWindowKey decodes the per-store portion of a join changelog key:
// uint32(len(kBytes)) | kBytes | int64(windowStart).
// Returns (nil, 0, false) on malformed input.
func ssJoinDecodeWindowKey(raw []byte) (kBytes []byte, windowStart int64, ok bool) {
	if len(raw) < 4+8 {
		return nil, 0, false
	}
	kLen := int(binary.BigEndian.Uint32(raw[0:4]))
	if len(raw) != 4+kLen+8 {
		return nil, 0, false
	}
	kb := make([]byte, kLen)
	copy(kb, raw[4:4+kLen])
	ws := int64(binary.BigEndian.Uint64(raw[4+kLen:]))
	return kb, ws, true
}

// ssJoinDumpChangelog is a debug helper: logs all entries in the changelog topic.
// Not called in production paths; left for diagnosing hangs.
func ssJoinDumpChangelog(t *testing.T, ctx context.Context, brokers []string, topic, storeName string) {
	t.Helper()
	serde := JSONSerde[string]{}
	readyCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	consumer, err := kgo.NewClient(
		kgo.SeedBrokers(brokers...),
		kgo.ConsumePartitions(map[string]map[int32]kgo.Offset{
			topic: {0: kgo.NewOffset().AtStart()},
		}),
	)
	if err != nil {
		t.Logf("ssJoinDumpChangelog: create consumer error: %v", err)
		return
	}
	defer consumer.Close()

	prefix := append([]byte(storeName), 0x00)
	for {
		fetches := consumer.PollFetches(readyCtx)
		if fetches.IsClientClosed() || readyCtx.Err() != nil {
			break
		}
		if fetches.Empty() {
			break
		}
		fetches.EachRecord(func(r *kgo.Record) {
			if !bytes.HasPrefix(r.Key, prefix) {
				return
			}
			kBytes, ws, ok := ssJoinDecodeWindowKey(r.Key[len(prefix):])
			if !ok {
				return
			}
			var strKey string
			if err := json.Unmarshal(kBytes, &strKey); err != nil {
				return
			}
			t.Logf("changelog %s: key=%q windowStart=%d value=%d bytes tombstone=%v",
				topic, strKey, ws, len(r.Value), len(r.Value) == 0)
			_ = serde
		})
	}
}
